/* Generated by Yosys 0.34+55 (git sha1 fa0a34062, gcc 7.5.0-6ubuntu2 -fPIC -Os) */

module top(clkin_data, in_data, out_data, probe_data);
  wire celloutsig_0z;
  wire celloutsig_1z;
  reg celloutsig_3z;
  wire celloutsig_5z;
  input [159:0] clkin_data;
  wire [159:0] clkin_data;
  input [95:0] in_data;
  wire [95:0] in_data;
  output [95:0] out_data;
  wire [95:0] out_data;
  output [31:0] probe_data;
  wire [31:0] probe_data;
  reg \out_data_reg[0] ;
  always_ff @(negedge clkin_data[0])
    if (!clkin_data[128])
      if (!clkin_data[64]) \out_data_reg[0]  <= 1'h1;
      else \out_data_reg[0]  <= celloutsig_3z;
  assign out_data[0] = \out_data_reg[0] ;
  assign celloutsig_5z = ~(celloutsig_0z & celloutsig_0z);
  assign celloutsig_0z = in_data[44:43] && in_data[5:4];
  assign celloutsig_1z = { celloutsig_0z, celloutsig_0z } != in_data[12:11];
  always_ff @(negedge clkin_data[32])
    if (clkin_data[128])
      if (clkin_data[96]) celloutsig_3z <= 1'h1;
      else celloutsig_3z <= celloutsig_1z;
  assign { out_data[32], out_data[1] } = { celloutsig_5z, 1'h1 };
endmodule
